/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fQ0iMYMqkiA
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";

export function Resume() {
  return (
    <div className="bg-background text-foreground font-inter">
      <header className="bg-black text-white py-8 px-6 md:px-12">
        <div className="container mx-auto flex flex-col items-center md:flex-row md:justify-between">
          <div className="flex items-center space-x-4 text-center md:text-left">
            <Avatar
              className="h-12 w-12"
              style={{
                position: "relative",
                display: "inline-flex",
                alignItems: "center",
                justifyContent: "center",
                overflow: "hidden",
                borderRadius: "50%",
                width: "3rem", // Adjust according to your sizing
                height: "3rem", // Adjust according to your sizing
              }}
            >
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div className="space-y-2">
              <h1 className="text-3xl font-bold">John Doe</h1>
              <p className="text-lg font-medium">Senior Product Manager</p>
            </div>
          </div>
          <div className="mt-4 md:mt-0 space-x-4 text-sm font-medium">
            <a href="#" className="hover:underline">
              john.doe@example.com
            </a>
            <a href="#" className="hover:underline">
              +1 (234) 567-890
            </a>
            <a href="#" className="hover:underline">
              linkedin.com/in/johndoe
            </a>
          </div>
        </div>
      </header>
      <main className="container mx-auto py-12 px-6 md:px-12 grid gap-12">
        <section>
          <h2 className="text-2xl font-bold mb-4">Work Experience</h2>
          <div className="space-y-8">
            <div>
              <h3 className="text-xl font-bold">Senior Product Manager</h3>
              <p className="text-muted-foreground">
                Acme Inc. | 2020 - Present
              </p>
              <ul className="mt-4 space-y-2 text-sm">
                <li>
                  Spearheaded the development and launch of a new product line
                  that generated $5M in revenue within the first year.
                </li>
                <li>
                  Led a cross-functional team of 10+ to define product roadmaps,
                  prioritize features, and ensure on-time delivery.
                </li>
                <li>
                  Implemented agile methodologies to improve development
                  efficiency, resulting in a 30% reduction in time-to-market.
                </li>
              </ul>
            </div>
            <div>
              <h3 className="text-xl font-bold">Product Manager</h3>
              <p className="text-muted-foreground">
                Widgets Inc. | 2017 - 2020
              </p>
              <ul className="mt-4 space-y-2 text-sm">
                <li>
                  Managed the product lifecycle for a suite of enterprise
                  software tools, driving a 25% increase in user adoption.
                </li>
                <li>
                  Collaborated with engineering, design, and sales teams to
                  define product requirements and deliver high-quality
                  solutions.
                </li>
                <li>
                  Analyzed market trends and customer feedback to inform product
                  strategy and roadmap planning.
                </li>
              </ul>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4">Education</h2>
          <div className="space-y-4">
            <div>
              <h3 className="text-xl font-bold">
                Master of Business Administration (MBA)
              </h3>
              <p className="text-muted-foreground">
                University of California, Berkeley | 2015 - 2017
              </p>
            </div>
            <div>
              <h3 className="text-xl font-bold">
                Bachelor of Science in Computer Science
              </h3>
              <p className="text-muted-foreground">
                University of California, Los Angeles | 2011 - 2015
              </p>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4">Skills</h2>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4 ">
            <div
              className="bg-muted rounded-lg p-4 bg-gray-200"
              style={{ borderRadius: "10px" }}
            >
              <h3 className="text-lg font-bold mb-2">Technical Skills</h3>
              <ul className="space-y-2 text-sm">
                <li>Product Management</li>
                <li>Agile Methodologies</li>
                <li>SQL and Data Analysis</li>
                <li>Project Management</li>
                <li>User Research</li>
              </ul>
            </div>
            <div
              className="bg-muted rounded-lg p-4 bg-gray-200"
              style={{ borderRadius: "10px" }}
            >
              <h3 className="text-lg font-bold mb-2">Soft Skills</h3>
              <ul className="space-y-2 text-sm">
                <li>Strategic Thinking</li>
                <li>Problem-Solving</li>
                <li>Communication</li>
                <li>Teamwork</li>
                <li>Leadership</li>
              </ul>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4">Achievements</h2>
          <div className="space-y-4">
            <div>
              <h3 className="text-xl font-bold">Product of the Year Award</h3>
              <p className="text-muted-foreground">Acme Inc. | 2022</p>
              <p className="text-sm">
                Recognized for leading the development and launch of a
                groundbreaking new product that disrupted the industry.
              </p>
            </div>
            <div>
              <h3 className="text-xl font-bold">Published Article</h3>
              <p className="text-muted-foreground">
                Product Management Magazine | 2021
              </p>
              <p className="text-sm">
                Authored a feature article on the importance of user-centric
                product design.
              </p>
            </div>
          </div>
        </section>
        <div className="flex justify-end gap-4">
          <Button
            variant="outline"
            style={{
              borderRadius: "20px",
              border: "1px solid #000", // Adjust the border color as needed
              padding: "10px 20px", // Adjust padding as needed
              background: "transparent",
              cursor: "pointer",
              transition: "background-color 0.3s ease",
              outline: "none",
            }}
          >
            Download as PDF
          </Button>
          <Button
            variant="outline"
            style={{
              borderRadius: "20px",
              border: "1px solid #000", // Adjust the border color as needed
              padding: "10px 20px", // Adjust padding as needed
              background: "transparent",
              cursor: "pointer",
              transition: "background-color 0.3s ease",
              outline: "none",
            }}
          >
            Edit Template
          </Button>
        </div>
      </main>
    </div>
  );
}
